version: '3.7'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

networks:
  app_network:
    driver: bridge

volumes:
  es_data: