version: '3.9'

services:
  server:
    build: ./
    volumes:
      - .:/app:ro
    ports:
      - "8888:8888"
    environment:
      - APP_PORT=8888
      - DB_HOST=elasticsearch
      - DB_PORT=9200
    depends_on:
      - elasticsearch
    networks:
      - app-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # ONLY FOR TESTING
      - xpack.security.transport.ssl.enabled=false   # ONLY FOR TESTING
      - xpack.security.http.ssl.enabled=false   # ONLY FOR TESTING
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

volumes:
  es_data:

networks:
  app-network:
    driver: bridge